---
title: 'Exercise: Linear Regression with Stan'
author: "Paul Bürkner"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
encoding: UTF-8
---

```{r, SETTINGS-knitr, include=FALSE}
# only relevant when knitting the document
options(width = 90)
knitr::opts_chunk$set(
  cache = FALSE,
  comment = NA,
  message = FALSE,
  warning = FALSE
)
```

Load required packages:
```{r, cache=FALSE}
library(rstan)
library(bayesplot)
theme_set(theme_default())
```

Load and plot data data:
```{r, echo=FALSE}
icecream <- read.csv("data/icecream.csv")
```

```{r, echo=FALSE, message = FALSE}
ggplot(icecream, aes(temp, units)) + 
  geom_point() 
```

Look at the Stan code:
```{r}
writeLines(readLines("stanmodels/linreg.stan"))
```

Prepare the data:
```{r}
sdata <- list(
  y = icecream$units,
  x = icecream$temp,
  N = nrow(icecream)
)
```

Fit the model:
```{r}
linreg_model <- stan(file = "stanmodels/linreg.stan", data = sdata)
```

Summarize the parameters:
```{r}
print(linreg_model)
```

Exercises: 

- Check model convergence numerically and graphically
- Perform posterior predictive checks
